bosses:
  zumbi:
    nome: "Zumbi"
    vida: 300
    head: 'f77e6e1ab179a3fa3cb487602af3f47643aedb1405caee71a138899951e14ea5'
    entidade: ZOMBIE
    recompensas:
      recompensa1:
        nome: "Espada de Ferro"
        itemstack:
          type: IRON_SWORD
          quantidade: 1
        comandos:
          - "give {player} minecraft:iron_sword 1"
      recompensa2:
        nome: "Ouro"
        itemstack:
          type: GOLD_INGOT
          quantidade: 10
        comandos:
          - "give {player} minecraft:gold_ingot 10"

  # Configurações do Esqueleto
  esqueleto:
    nome: "Esqueleto"
    vida: 300
    head: '377055cadacbb0f8f35c1d18acc2ed86e0bcc6d73dda71e4c59f7ea28b7b27b6'
    entidade: SKELETON
    recompensas:
      recompensa1:
        nome: "Arco"
        itemstack:
          type: BOW
          quantidade: 1
        comandos:
          - "give {player} minecraft:bow 1"
      recompensa2:
        nome: "Flechas"
        itemstack:
          type: ARROW
          quantidade: 20
        comandos:
          - "give {player} minecraft:arrow 20"

  # Configurações do Enderman
  enderman:
    nome: "Enderman"
    vida: 300
    head: '37c0d010dd0e512ffea108d7c5fe69d576c31ec266c884b51ec0b28cc457'
    entidade: ENDERMAN
    recompensas:
      recompensa1:
        nome: "Diamante"
        itemstack:
          type: DIAMOND
          quantidade: 5
        comandos:
          - "give {player} minecraft:diamond 5"
      recompensa2:
        nome: "Barra de Ouro"
        itemstack:
          type: GOLD_INGOT
          quantidade: 3
        comandos:
          - "give {player} minecraft:gold_ingot 3"
